spring:
  datasource:
    url: jdbc:postgresql://localhost:9400/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          fetch_size: 50
          batch_size: 20
          use_scrollable_resultset: true

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
jwt:
  secret: wb2H7b9etkXapRG4ewH1jdj1qetuz/sSPzyQi+ShjEg=
  expiration: 1800000
